import type { LayoutMap } from "../keys";

export const staticaLayoutUnshifted: LayoutMap = {
  keyBackquote: "ё",
  key1: "!",
  key2: '"',
  key3: "№",
  key4: "ъ",
  key5: "%",
  key6: "Ъ",
  key7: "?",
  key8: "*",
  key9: "(",
  key0: ")",
  keyMinus: "-",
  keyEqual: "=",

  keyQ: "ь",
  keyW: "у",
  keyE: "а",
  keyR: "ж",
  keyT: "ю",
  keyY: "г",
  keyU: "б",
  keyI: "р",
  keyO: "л",
  keyP: "х",
  keyLbracket: "щ",
  keyRbracket: "ф",

  keyA: "и",
  keyS: "е",
  keyD: "о",
  keyF: "к",
  keyG: "я",
  keyH: "м",
  keyJ: "т",
  keyK: "с",
  keyL: "н",
  keySemicolon: "з",
  keyQuote: ".",
  keyBackslash: "/",

  keyZ: "э",
  keyX: "ы",
  keyC: "п",
  keyV: "й",
  keyB: ",",
  keyN: "д",
  keyM: "в",
  keyComma: "ч",
  keyPeriod: "ш",
  keySlash: "ц",
  keySpace: " ",
};

export const staticaLayoutShiftedOverrides: LayoutMap = {
  // Matches the "С шифтом" mapping in the provided reference:
  // digits become digits, punctuation varies by position.
  key1: "1",
  key2: "2",
  key3: "3",
  key4: "4",
  key5: "5",
  key6: "6",
  key7: "7",
  key8: "8",
  key9: "9",
  key0: "0",
  keyMinus: "_",
  keyEqual: "+",
  keyQuote: ":",
  keyBackslash: "/",
  keyB: ";",
};
