import type { LayoutMap } from "../keys";

export const staticaLayoutUnshifted: LayoutMap = {
  keyBackquote: "ё",
  key1: "!",
  key2: '"',
  key3: "№",
  key4: "ъ",
  key5: "%",
  key6: "Ъ",
  key7: "?",
  key8: "*",
  key9: "(",
  key0: ")",
  keyMinus: "-",
  keyEqual: "=",

  keyQ: "ь",
  keyW: "у",
  keyE: "а",
  keyR: "ж",
  keyT: "ю",
  keyY: "г",
  keyU: "б",
  keyI: "р",
  keyO: "л",
  keyP: "х",
  keyLbracket: "щ",
  keyRbracket: "ф",

  keyA: "и",
  keyS: "е",
  keyD: "о",
  keyF: "к",
  keyG: "я",
  keyH: "м",
  keyJ: "т",
  keyK: "с",
  keyL: "н",
  keySemicolon: "з",
  keyQuote: ".",
  keyBackslash: "ц",

  keyZ: "\\",
  keyX: "э",
  keyC: "ы",
  keyV: "п",
  keyB: "й",
  keyN: ",",
  keyM: "д",
  keyComma: "в",
  keyPeriod: "ч",
  keySlash: "ш",
  keySpace: " ",
};
